/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesramen;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Asus
 */
public class lihatAdmin extends javax.swing.JFrame {
    private static Connection sambung;
    private static Statement stat;
    
    private DefaultTableModel tab;
    
    private void daftar (){
        Object[]baris ={"karageramen","katsuramen","saugeramen","tofuramen","drumbstickramen","tebasakiramen","crabstick","ekado","udon","kerupuk","iceTea","lemonTea","iceCream","pancake"};
        tab =new DefaultTableModel(null,baris);
        pesanan.setModel(tab);
        String sql = "SELECT *from `daftar` order by karageramen asc";
                //+ "//katsuramen,saugeramen,tofuramen,tofuramen,tebasakiramen,crabstickramen'
                //"order by karageramen asc ";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sambung=DriverManager.getConnection("jdbc:mysql://localhost:3306/datamenu?zeroDateTimeBehavior=convertToNull", "root", "");
            JOptionPane.showMessageDialog(null, "Tersambung");
            stat = sambung.createStatement();
            ResultSet hasil = stat.executeQuery(sql);;
            while (hasil.next()){
                String karageramen =hasil.getString("karageramen");
                String katsuramen =hasil.getString("katsuramen");
                String saugeramen =hasil.getString("saugeramen");
                String tofuramen =hasil.getString("tofuramen");
                String tebasakiramen =hasil.getString("tebasakiramen");
                String crabstickramen =hasil.getString("crabstickramen");
                String ekadoramen =hasil.getString("ekado");
                String udonramen =hasil.getString("udon");
                String kerupukramen =hasil.getString("kerupuk");
                String icetea=hasil.getString("icetea");
                String lemontea =hasil.getString("lemontea");
                String icecream =hasil.getString("icetea");
                String pancake =hasil.getString("pancake");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR Gagal Memuat KeDatabase");
        
        }
      
        
        
    }
    

    
    
    
   

    /**
     * Creates new form lihatAdmin
     */
    public lihatAdmin() {
        initComponents();
        daftar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cari.setText("cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "karageramen", "katsuramen", "saugeramen", "tofuramen", "drumbstickramen", "tebasakiramen", "crabstick", "ekado", "udon", "kerupuk", "icetea", "lemontea", "ice cream", "pancake", "kuah", "level", "Title 17"
            }
        ));
        jScrollPane1.setViewportView(pesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(cari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(cari)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        
          
          //panggil pesanan
          
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pesanan;
    // End of variables declaration//GEN-END:variables
}
