/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesramen;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 8
 */
public class loginPembeli extends javax.swing.JFrame {
 private static Connection connec;
 public static Statement st;
 private void data (){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connec=DriverManager.getConnection("jdbc:mysql://localhost:3306/yuhu", "root", "");
            st = connec.createStatement();
            JOptionPane.showMessageDialog(null, "Tersambung");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memuat KeDatabase, Aktifkan Database Sebelum Memulai");
        }
    }
 
 private String dtbs="";
     private String emailSimpan="", passwordSimpan="";

    
   
    /**
     * Creates new form loginPembeli
     */
    public loginPembeli() {
        initComponents();
        data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tulisanEmail = new javax.swing.JLabel();
        tulisanPassword = new javax.swing.JLabel();
        masukanEmailPembeli = new javax.swing.JTextField();
        masukanPasswordPembeli = new javax.swing.JTextField();
        regrisAkunPembeli = new javax.swing.JButton();
        loginPembeli = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tulisanEmail.setText("EMAIL");

        tulisanPassword.setText("PASSWORD");

        masukanEmailPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukanEmailPembeliActionPerformed(evt);
            }
        });

        regrisAkunPembeli.setText("BUAT AKUN");
        regrisAkunPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regrisAkunPembeliActionPerformed(evt);
            }
        });

        loginPembeli.setText("LOGIN");
        loginPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPembeliActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASUKKAN EMAIL DAN PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(loginPembeli)
                        .addGap(98, 98, 98)
                        .addComponent(regrisAkunPembeli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tulisanPassword)
                            .addComponent(tulisanEmail))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(masukanPasswordPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(masukanEmailPembeli))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tulisanEmail)
                    .addComponent(masukanEmailPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tulisanPassword)
                    .addComponent(masukanPasswordPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPembeli)
                    .addComponent(regrisAkunPembeli))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPembeliActionPerformed
         String emailSimpan =String.valueOf(masukanEmailPembeli.getText());
         String passwordSimpan =String.valueOf(masukanPasswordPembeli.getText());
          try{
            dtbs="SELECT * FROM `data` WHERE Email='"+emailSimpan+"' and Password='"+passwordSimpan+"'";
            System.out.println(dtbs);
            st=connec.createStatement();
            //st.execute(dtbs);
            ResultSet rss = st.executeQuery(dtbs);
            //Clear();
            //ShowData(sql);
            menu m = new menu();
            m.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Belum Terdaftar"+e.getMessage());
        }

    }//GEN-LAST:event_loginPembeliActionPerformed

    private void regrisAkunPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regrisAkunPembeliActionPerformed
        registrasi r = new registrasi();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regrisAkunPembeliActionPerformed

    private void masukanEmailPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukanEmailPembeliActionPerformed
        
    }//GEN-LAST:event_masukanEmailPembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginPembeli;
    private javax.swing.JTextField masukanEmailPembeli;
    private javax.swing.JTextField masukanPasswordPembeli;
    private javax.swing.JButton regrisAkunPembeli;
    private javax.swing.JLabel tulisanEmail;
    private javax.swing.JLabel tulisanPassword;
    // End of variables declaration//GEN-END:variables
}
